[package]
name = "eslx_freeswitcheslrs_events"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "eslx_freeswitcheslrs_events"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
freeswitch-esl-rs = "0.3.1"
